import{i as u,a as m,A as p}from"./assets/vendor-b5a3dDts.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();let f={};const n={formEl:document.querySelector(".order-form"),backdropEl:document.querySelector(".order-backdrop"),closeBtn:document.querySelector(".modal-close-button"),phoneInput:document.getElementById("phone")};n.phoneInput.addEventListener("input",()=>{let e=n.phoneInput.value.replace(/\D/g,"");e.startsWith("0")?e="38"+e:e.startsWith("8")&&(e="3"+e),e=e.slice(0,12),n.phoneInput.value=e});n.closeBtn.addEventListener("click",l);n.backdropEl.addEventListener("click",e=>{e.target===n.backdropEl&&l()});document.addEventListener("keydown",e=>{e.key==="Escape"&&n.backdropEl.classList.contains("is-open")&&l()});n.formEl.addEventListener("submit",async e=>{e.preventDefault();const{name:t,phone:s,comment:c}=e.target.elements;if(!/^380\d{9}$/.test(s.value)){e.preventDefault(),u.show({message:"Введіть номер у форматі 380XXXXXXXXX"});return}t.value.length===1&&u.show({message:"Ім'я має бути мінімум 2 символи!",color:"red"});const o=y(c.value);f={name:t.value,phone:s.value,comment:o,modelId:"682f9bbf8acbdf505592ac36",color:"#1212ca"},console.log(f);try{const d=(await m.post("https://furniture-store-v2.b.goit.study/api/orders",f)).data;console.log(d),u.show({message:`Ви замовили ${d.model}! 
    Hомер замовлення ${d.orderNum}. 
    Вже телефонуємо Вам 🫶`,color:"green"}),e.target.reset(),l()}catch(i){e.preventDefault(),console.log(i.message),u.show({message:"Некорректні дані, будь ласка, перевірте форму на помилки!",color:"red"})}});function g(){document.body.style.overflow=""}function l(){n.backdropEl.classList.remove("is-open"),g()}function y(e){if(e.length>256)return e.slice(0,255);for(;e.length<5;)e+=" ";return e}const h="https://furniture-store-v2.b.goit.study/api/categories",b="https://furniture-store-v2.b.goit.study/api/furnitures";async function L(){try{const{data:e}=await m.get(h);return e}catch(e){return console.error("Error fetching categories:",e),[]}}async function v(){const{data:e}=await m.get(b,{params:{page:1,limit:8}});return e.furnitures}const a={header:document.querySelector(".header"),furnitureCategoryList:document.querySelector(".furniture-category__list"),furnitureList:document.querySelector(".furniture-list"),accordionContainer:document.querySelector(".accordion"),orderBackdrop:document.querySelector(".order-backdrop"),orderModalOverlay:document.querySelector(".order-modal-overlay"),productModal:document.querySelector(".product-modal"),productModalCloseBtn:document.querySelector(".product-modal__close")},k={"М'які меблі":"soft-furniture","Шафи та системи зберігання":"storage-systems","Ліжка та матраци":"beds-mattresses",Столи:"tables","Стільці та табурети":"chairs-stools",Кухні:"kitchens","Меблі для дитячої":"kids-furniture","Меблі для офісу":"office-furniture","Меблі для передпокою":"hallway-furniture","Меблі для ванної кімнати":"bathroom-furniture","Садові та вуличні меблі":"garden-furniture","Декор та аксесуари":"decor-accessories"};function E({id:e,name:t}){return`
    <li class="furniture-category__item ${k[t]||""}" data-id="${e}">
      <a href="#" class="furniture-category__link">${t}</a>
    </li>`}function w(e){return e.map(E).join("")}function S(e){if(!a.furnitureCategoryList){console.error("Елемент .furniture-category__list не знайдено!");return}const t=w(e);a.furnitureCategoryList.insertAdjacentHTML("beforeend",t)}async function C(){const e=await L();e.length>0&&S(e)}function $({_id:e,name:t,price:s,images:c,color:r}){const o=r.map(i=>`<span class="color-dot" style="background-color: ${i}"></span>`).join("");return`
    <li class="furniture-card" data-id="${e}">
      <img
        src="${c[0]}" 
        alt="${t}"
        class="card-image"
        loading="lazy"
      />
      <h2 class="card-title">${t}</h2>
      <div class="card-colors">
        ${o}
      </div>
      <p class="card-price">${s.toLocaleString()} грн</p>
      <button class="details-btn" type="button" data-id="${e}">Детальніше</button>
    </li>`}function q(e){return e.map($).join("")}function _(e){if(!a.furnitureList){console.error("Елемент .furniture-list не знайдено!");return}const t=q(e);a.furnitureList.insertAdjacentHTML("beforeend",t)}async function M(){const e=await v();e&&e.length>0&&_(e),console.log(e)}function I(){const e=document.querySelector(".accordion");e&&new p(e,{duration:300,showMultiple:!1,collapse:!0})}function O(){a.furnitureCategoryList&&a.furnitureCategoryList.addEventListener("click",e=>{const t=e.target.closest(".furniture-category__item");if(!t)return;a.furnitureCategoryList.querySelectorAll(".furniture-category__item").forEach(c=>c.classList.remove("akcent-item-color")),t.classList.add("akcent-item-color")})}document.addEventListener("DOMContentLoaded",()=>{console.log("DOM fully loaded and parsed"),I(),C(),O(),M()});
//# sourceMappingURL=index.js.map
